version: "3.7"

services:
  apis:
    container_name: apis
    build:
      context: ./chicken
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - ./apis:/usr/src/app
